sequenceDiagram
    actor User

    %% Flow 3: Viewing Reservations
    User->>+MeetingRoom: listBookings()
    MeetingRoom->>MeetingRoom: Retrieve bookings list
    MeetingRoom-->>User: List of Bookings